### ISSUE TITLE
Demo looks like broken

### ISSUE THREAD

**Issue by Ohar** [strawstack/text-bubbles-for-phaser#1]

**Comment by strawstack** [comment]
Hello, thanks for raising the issue! I’ll take a look in the next few days :)

**Comment by strawstack** [comment]
It's fixed now. There was an issue with gh-pages serving the page. I had to make another empty commit to trigger a redeployment: http://xn--qxa.ws/Text-Bubbles-for-PhaserJS/

**Comment by Ohar** [comment]
Oh, many thanks! It [looks](http://xn--qxa.ws/Text-Bubbles-for-PhaserJS/) nice now!
